# Generated by Django 4.2.6 on 2024-01-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistModel',
        ),
    ]
