# Generated by Django 4.2.6 on 2023-10-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_userprofile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product_id',
            new_name='product',
        ),
    ]
