# Generated by Django 4.2.6 on 2024-01-10 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_userorder_userorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorderitem', to='Store.userorder'),
        ),
    ]
