# Generated by Django 4.2.6 on 2024-01-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_userorder_user_alter_userorderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderitem',
            name='coupon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userorderitem',
            name='total',
            field=models.CharField(max_length=250),
        ),
    ]
