# Generated by Django 4.2.6 on 2023-10-23 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_rename_sub_category_id_product_sub_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(upload_to='main_img/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
