# Generated by Django 4.2.6 on 2024-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_userorderitem_coupon_alter_userorderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
