# Generated by Django 4.2.6 on 2024-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_userorder_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrderItem',
        ),
    ]
