# Generated by Django 4.2.6 on 2023-10-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
