# Generated by Django 4.2.6 on 2023-11-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_brand_colorr_sizee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('slug', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('specs', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.brand')),
                ('categoryy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.categoryy')),
                ('colorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.colorr')),
                ('sizee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.sizee')),
            ],
        ),
    ]
