# Generated by Django 4.2.6 on 2024-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_userorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorderitem',
            name='coupon',
            field=models.CharField(max_length=250),
        ),
    ]
