# Generated by Django 4.2.6 on 2023-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_productt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productt',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
