# Generated by Django 4.2.6 on 2023-11-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_productt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('colorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.colorr')),
                ('productt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.productt')),
                ('sizee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.sizee')),
            ],
        ),
    ]
