# Generated by Django 4.2.6 on 2023-11-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryy',
            options={'verbose_name_plural': 'Categoriess'},
        ),
    ]
