# Generated by Django 4.2.6 on 2023-11-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_alter_categoryy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='colorr',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='productt',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='sizee',
        ),
        migrations.RemoveField(
            model_name='productt',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productt',
            name='categoryy',
        ),
        migrations.RemoveField(
            model_name='productt',
            name='colorr',
        ),
        migrations.RemoveField(
            model_name='productt',
            name='sizee',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Categoryy',
        ),
        migrations.DeleteModel(
            name='colorr',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='Productt',
        ),
        migrations.DeleteModel(
            name='sizee',
        ),
    ]
