# Generated by Django 4.2.6 on 2023-11-16 05:48

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_remove_productattribute_colorr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', validators=[Store.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='logo',
            name='cover_image',
            field=models.ImageField(upload_to='Logo_img/', validators=[Store.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='main_images',
            name='cover_image',
            field=models.ImageField(upload_to='main_img/', validators=[Store.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cover_image',
            field=models.ImageField(upload_to='product/', validators=[Store.models.validate_image_type]),
        ),
    ]
