# Generated by Django 4.2.6 on 2023-11-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_category_image_alter_logo_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.variant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='variant_qty',
            field=models.IntegerField(null=True),
        ),
    ]
