# Generated by Django 4.2.6 on 2023-11-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_colorimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorimage',
            old_name='cover_image',
            new_name='variantimg',
        ),
    ]
