# Generated by Django 4.2.6 on 2023-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_userdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variant_qty',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
