# Generated by Django 4.2.6 on 2023-11-28 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_cart_total_price_alter_cart_variant_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peromocode', models.CharField(max_length=10)),
                ('discount_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('expaire_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
