# Generated by Django 4.2.6 on 2023-11-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_peromocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeromoCode',
        ),
    ]
