# Generated by Django 4.2.6 on 2023-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_delete_peromocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peromocode', models.CharField(max_length=10)),
                ('discount_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('expaire_date', models.DateField()),
            ],
        ),
    ]
