# Generated by Django 4.2.6 on 2023-11-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_peromocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peromocode',
            old_name='peromocode',
            new_name='code',
        ),
    ]
