# Generated by Django 4.2.6 on 2023-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0028_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
