# Generated by Django 4.2.6 on 2023-12-20 10:22

import Store.models
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorimage',
            name='variantimg',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[Store.models.validate_image_type]),
        ),
    ]
