# Generated by Django 4.2.6 on 2023-12-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0031_alter_colorimage_variantimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeromoCode',
            new_name='PromoCode',
        ),
    ]
